name: climator
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  geolocator: ^10.1.0
  flutter_spinkit: ^5.1.0
  http: ^1.1.0
  url_launcher: ^6.0.17
#  fluttertoast: ^8.0.8
  another_flushbar: ^1.12.30
  google_fonts: ^6.1.0
  flutter_dotenv: ^5.1.0
  dio: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
  - images/weather_icons/
  - dev.env
